default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: hometime-reservation-api-dev

test:
  <<: *default
  database: hometime-reservation-api-test
